[package]
name = "fluorite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluorite-common = { path = "fluorite-common" }
fluorite-arm = { path = "fluorite-arm" }

log = "0.4.14"
color-eyre = "0.5.11"
simple_logger = "1.13.0"

[build-dependencies]
fluorite-common = { path = "fluorite-common" }

[workspace]
members = [
	"fluorite-common",
	"fluorite-arm"
]