[workspace]
members = [
	"fluorite-frontend",
	"fluorite-common",
	"fluorite-common/macros",
	"fluorite-gba"
]

[profile.dev]
overflow-checks = false

[profile.release]
lto = true
codegen-units = 1
debug = true