[package]
name = "fluorite-gba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
num = "0.4.0"
priority-queue = "1.2.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"